[tasks.default]
clear = true
script = [
    "echo '\n\nNo default task.  Try:\n  `cargo make wurstscript`, or\n  `cargo make grill`\n\n'"
]

[tasks.wurstscript]
linux_alias = "linux_wurstscript"
windows_alias = "windows_wurstscript"

[tasks.windows_wurstscript]
script = [
    'echo "wurstscript.jar" > src/jar.tmp',
    "cargo build --release"
]

[tasks.linux_wurstscript]
script = [
    "echo \\\"wurstscript.jar\\\" > src/jar.tmp",
    "cargo build --release"
]

[tasks.grill]
linux_alias = "linux_grill"
windows_alias = "windows_grill"

[tasks.windows_grill]
script = [
    'echo "wurstsetup.jar" > src/jar.tmp',
    "cargo build --release"
]

[tasks.linux_grill]
script = [
    "echo \\\"wurstsetup.jar\\\" > src/jar.tmp",
    "cargo build --release"
]

# Cross-compilation

[tasks.wurstscript_for_windows_from_linux_crosscompile]
script = [
    "echo \\\"wurstscript.jar\\\" > src/jar.tmp",
    "cargo build --release --target x86_64-pc-windows-gnu"
]

[tasks.grill_for_windows_from_linux_crosscompile]
script = [
    "echo \\\"wurstsetup.jar\\\" > src/jar.tmp",
    "cargo build --release --target x86_64-pc-windows-gnu"
]
